baseURL = 'https://edparry.com/'
languageCode = 'en-us'
title = 'Ed Parry'
theme = 'stream'

[params]
  author = 'Ed Parry'
  description = 'Stream of thoughts'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
