baseURL = 'https://ed-parry.github.io/'
languageCode = 'en-us'
title = 'Ed Parry'
theme = 'stream'

[params]
  author = 'Ed Parry'
  description = 'What I write about what I think'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
